# Generated by Django 2.1.7 on 2020-04-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomaero', models.CharField(max_length=50, verbose_name='Nom Aérodrome')),
                ('codeoaciaero', models.CharField(max_length=50, verbose_name='Code OACI')),
                ('localiteaero', models.CharField(default='', max_length=50, verbose_name='Localité')),
                ('coordLataero', models.CharField(max_length=30, verbose_name='Latitude ')),
                ('coordLongaero', models.CharField(max_length=30, verbose_name='Longitude ')),
                ('gestionaero', models.CharField(default='', max_length=50, verbose_name='Gestionnaire')),
                ('contactgestionaero', models.CharField(default='', max_length=50, verbose_name='Contact Gestionnaire')),
                ('aerointernational', models.BooleanField(default=False, verbose_name='Aéroport international')),
                ('statutaero', models.CharField(choices=[('CERTIF', 'Certifié'), ('ACERTI', 'A certifier'), ('HOMOLO', 'Homologué'), ('AHOMOL', 'A homologuer')], max_length=6)),
                ('conformiteaero', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Conformité aérodrome en %')),
                ('descripaero', models.TextField(null=True, verbose_name='Description Aérodrome')),
                ('illustrationaero', models.FileField(default='fichierdefaut.pdf', upload_to='illustrations/%Y/%m/%d/', verbose_name='Illustrations Aérodrome')),
            ],
        ),
        migrations.CreateModel(
            name='Agentac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculeag', models.CharField(max_length=20, verbose_name='Matricule Agent')),
                ('prenomsag', models.CharField(max_length=50, verbose_name='Prénom(s) Agent')),
                ('nomag', models.CharField(max_length=30, verbose_name='Nom Agent')),
                ('fonctionag', models.CharField(default='Inspecteur', max_length=50, verbose_name='Fonction Agent')),
                ('naissanceag', models.DateField(verbose_name='Date de naissance ')),
                ('lieunaisag', models.CharField(default='Dakar', max_length=50, verbose_name='Lieu de naissance')),
                ('descripag', models.TextField(null=True, verbose_name='Apropos Agent')),
                ('photoagent', models.ImageField(default='fichierdefaut.pdf', upload_to='agents/photos/%Y/%m/%d/', verbose_name='Photo')),
            ],
            options={
                'ordering': ['nomag'],
            },
        ),
        migrations.CreateModel(
            name='Bureauac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombur', models.CharField(max_length=30)),
                ('descripbur', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choixdepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript', models.TextField(null=True, verbose_name='Description Choix')),
            ],
        ),
        migrations.CreateModel(
            name='Departementac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdep', models.CharField(max_length=30)),
                ('descripdep', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directionac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdir', models.CharField(max_length=30)),
                ('descripdir', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomaineInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdomaineinsp', models.CharField(max_length=30, verbose_name="Domaine d'inspecion ")),
                ('checklistdomaineinsp', models.FileField(default='fichierdefaut.pdf', upload_to='checklist/%Y/%m/%d/', verbose_name='Checklist')),
                ('descripdomaineinsp', models.TextField(null=True, verbose_name='Description Domaine Inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Dossieraerodrome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptiondossier', models.TextField(blank=True, null=True, verbose_name='Description Dossier Aérodrome')),
                ('datedoc', models.DateField(verbose_name='Date de production du document ')),
                ('dossieraero', models.FileField(default='fichierdefaut.pdf', upload_to='dossiers/aerodromes/%Y/%m/%d/', verbose_name='Document Aérodrome')),
                ('codeaerodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Aerodrome', verbose_name='Nom Aérodrome')),
            ],
        ),
        migrations.CreateModel(
            name='Dossieragent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptiondocumentagent', models.TextField(blank=True, null=True, verbose_name='Description Dossier Agent')),
                ('datedocumentagent', models.DateField(default='2020-02-13', verbose_name='Date de production du document ')),
                ('dossieragent', models.FileField(default='fichierdefaut.pdf', upload_to='dossiers/agent/%Y/%m/%d/', verbose_name='Document Agent')),
                ('codeagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Agentac', verbose_name='Matricule Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Dossierevenementsecu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptiondocumentevt', models.TextField(blank=True, null=True, verbose_name='Description Dossier Evénement')),
                ('datedocumentevt', models.DateField(default='2020-02-13', verbose_name='Date de production du document ')),
                ('dossierevt', models.FileField(default='fichierdefaut.pdf', upload_to='dossiers/evt/%Y/%m/%d/', verbose_name='Document Evénement')),
            ],
        ),
        migrations.CreateModel(
            name='Dossierformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description Dossier Formation')),
                ('datedocument', models.DateField(default='2020-02-13', verbose_name='Date de production du document ')),
                ('dossierformation', models.FileField(default='fichierdefaut.pdf', upload_to='dossiers/formations/%Y/%m/%d/', verbose_name='Document Formation')),
            ],
        ),
        migrations.CreateModel(
            name='Dossierinspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description Dossier Inspection')),
                ('datedocument', models.DateField(default='2020-02-13', verbose_name='Date de production du document ')),
                ('dossierinsp', models.FileField(default='fichierdefaut.pdf', upload_to='dossiers/%Y/%m/%d/', verbose_name='Document Inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Evtsecurite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeevt', models.CharField(editable=False, max_length=150)),
                ('typeevt', models.CharField(choices=[('ANS', 'Approche non conforme'), ('PIN', 'Position inusuelle'), ('ECA', 'Evt lié aux conditions aerodrome'), ('SAI', 'Mise en oeuvre inadaptée des systèmes aéronef'), ('TRM', 'Travaux et maintenance'), ('MCO', 'Mauvaise coordination et opérations sol'), ('INC', 'Incursion sur piste'), ('PSV', 'Perte séparation en vol'), ('PES', 'Pénétration espace'), ('EXP', 'Exploitation'), ('PAN', 'Péril animalier dont aviaire'), ('FDG', 'Feux Dangereux, lasers'), ('MET', 'Météo'), ('DIB', 'Défaillance interfaces sol-bord'), ('EEA', 'Evt relatif entretien aeronef'), ('FFV', 'Feu-fumée en vol ou au sol'), ('DSB', 'Défaillance système à bord'), ('DPR', 'Dépressurisation'), ('FOD', 'Dommage suite FOD'), ('AUT', 'Autre')], max_length=3, verbose_name='Type Evt Sécu')),
                ('lieuevt', models.CharField(max_length=30, verbose_name='Lieu Evt Sécu')),
                ('latitudeevt', models.CharField(max_length=30, verbose_name='Latitude Evt Sécu')),
                ('longitudeevt', models.CharField(max_length=30, verbose_name='Longitude Evt Sécu')),
                ('dateevt', models.DateField(verbose_name='Date Evt Sécu ')),
                ('heureevt', models.TimeField(verbose_name='Heure Evt Sécu ')),
                ('notifiantevt', models.CharField(max_length=30, verbose_name='Notifiant Evt Sécu')),
                ('immataeronefevt', models.CharField(default='NA', max_length=30, verbose_name='Immatriculation aéronef')),
                ('classeevt', models.CharField(choices=[('INC', 'Incident'), ('IGR', 'Incident Grave'), ('ACC', 'Accident')], default='INC', max_length=3, verbose_name='Classe Evt')),
                ('statutevt', models.CharField(choices=[('ENC', 'Ouvert, analyse en cours'), ('CAD', 'Clos avec analyse détaillée'), ('CAS', 'Clos avec analyse sommaire')], default='ENC', max_length=3, verbose_name='Statut Evt')),
                ('groupeanimalevt', models.CharField(choices=[('OIS', 'Oiseaux'), ('ATA', 'Autre animal'), ('NEA', 'NA')], default='NEA', max_length=3, verbose_name='Groupe animal Evt')),
                ('nomanimalevt', models.CharField(default='NA', max_length=30, verbose_name='Nom animal Evt Sécu')),
                ('descripinsp', models.TextField(null=True, verbose_name='Description Evt Sécu')),
                ('notifevt', models.FileField(upload_to='evt_securite/%Y/%m/%d/', verbose_name='Notification evt')),
                ('nomaero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Aerodrome', verbose_name='Aérodrome')),
            ],
        ),
        migrations.CreateModel(
            name='Formationac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeform', models.CharField(max_length=20, verbose_name='Codification')),
                ('nomform', models.CharField(max_length=30, verbose_name='Intitulé de la formation')),
                ('specialiteform', models.BooleanField(default=True)),
                ('realiseform', models.BooleanField(default=False)),
                ('typeformation', models.CharField(choices=[('PLG', 'Planifiée'), ('HPL', 'Hors Planning')], default='PLG', max_length=3, verbose_name='Type')),
                ('periodicform', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=2, verbose_name='Périodicité')),
                ('descripform', models.TextField(null=True, verbose_name='Description')),
                ('debutforma', models.DateField(null=True, verbose_name='Date de début')),
                ('finforma', models.DateField(null=True, verbose_name='Date de fin')),
                ('lieuforma', models.CharField(max_length=30, verbose_name='Lieu de formation')),
                ('coutform', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Coût Formation en CFA')),
                ('docdescriptif', models.FileField(default='fichierdefaut.pdf', upload_to='dossiers/formations/%Y/%m/%d/', verbose_name='Document Formation')),
                ('agentaformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Agentac', verbose_name='Matricule Agent')),
            ],
            options={
                'ordering': ['debutforma'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeinsp', models.CharField(editable=False, max_length=150)),
                ('datedebutinsp', models.DateField(verbose_name='Début inspection ')),
                ('datefininsp', models.DateField(verbose_name='Fin inspection ')),
                ('typeinsp', models.CharField(choices=[('PER', 'Périodique'), ('INO', 'Inopiné'), ('AUT', 'Autre')], max_length=3)),
                ('zoneinsp', models.CharField(choices=[('aibd', 'AIBD'), ('louis', 'St Louis'), ('tamba', 'Tamba'), ('zig', 'Ziguinchor'), ('cap', 'Cap Skirring'), ('centre', 'Zone Centre'), ('est', 'Zone Est'), ('nord', 'Zone Nord'), ('sud', 'Zone Sud-Est')], default='', max_length=5, verbose_name='Zone Aérodrome')),
                ('insprealisee', models.BooleanField(default=False, verbose_name='Réalisée')),
                ('inspentamee', models.BooleanField(default=False, verbose_name='Entamée')),
                ('descripinsp', models.TextField(null=True, verbose_name='Description Inspection')),
                ('coutinsp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût Inspection en CFA')),
                ('rapportinsp', models.FileField(default='fichierdefaut.pdf', upload_to='aerodromes/%Y/%m/%d/', verbose_name='Rapport Inspection')),
                ('agentac', models.ManyToManyField(to='aerodromes.Agentac', verbose_name='Equipe Inspection')),
                ('domaineinsp', models.ManyToManyField(to='aerodromes.DomaineInspection', verbose_name='Domaine(s) Inspection')),
                ('nomaero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Aerodrome', verbose_name='Aérodrome')),
                ('nomdepartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Departementac', verbose_name='Département en charge')),
            ],
        ),
        migrations.CreateModel(
            name='Positionequipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudeposi', models.CharField(max_length=30, verbose_name='Latitude ')),
                ('longitudeposi', models.CharField(max_length=30, verbose_name='Longitude ')),
                ('descripposi', models.TextField(null=True, verbose_name='Description Position')),
            ],
        ),
        migrations.CreateModel(
            name='Serviceac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomser', models.CharField(max_length=30, verbose_name='Nom Service')),
                ('descripser', models.TextField(null=True, verbose_name='Description Service')),
                ('departementac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Departementac', verbose_name='Département Service')),
            ],
        ),
        migrations.CreateModel(
            name='Trajetmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyentrans', models.CharField(choices=[('VOIT', 'Voiture'), ('AVIO', 'Avion')], max_length=4)),
                ('descriptrajet', models.TextField(null=True, verbose_name='Description Trajet')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Inspection', verbose_name='Inspection')),
                ('positionequipes', models.ManyToManyField(to='aerodromes.Positionequipe', verbose_name='Points du trajet')),
            ],
        ),
        migrations.AddField(
            model_name='dossierinspection',
            name='codeinspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Inspection', verbose_name='Code Inspection'),
        ),
        migrations.AddField(
            model_name='dossierformation',
            name='codeformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Formationac', verbose_name='Code Formation'),
        ),
        migrations.AddField(
            model_name='dossierevenementsecu',
            name='codeevenementsecu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Evtsecurite', verbose_name='Code Evénement Sécurité'),
        ),
        migrations.AddField(
            model_name='domaineinspection',
            name='servicedomaineinsp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Serviceac', verbose_name='Service Responsable'),
        ),
        migrations.AddField(
            model_name='departementac',
            name='directionac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Directionac'),
        ),
        migrations.AddField(
            model_name='choixdepartement',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Departementac', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='bureauac',
            name='serviceac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Serviceac'),
        ),
        migrations.AddField(
            model_name='agentac',
            name='serviceac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Serviceac', verbose_name='Service Agent'),
        ),
    ]
