# Generated by Django 2.1.7 on 2020-04-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerodromes', '0002_auto_20200416_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='zoneinsp',
            field=models.CharField(choices=[('aibd', 'AIBD'), ('louis', 'St Louis'), ('tamba', 'Tamba'), ('zig', 'Ziguinchor'), ('cap', 'Cap Skirring'), ('centre', 'Zone Centre'), ('est', 'Zone Est'), ('nord', 'Zone Nord'), ('sud', 'Zone Sud-Est')], default='', max_length=6, verbose_name='Zone Aérodrome'),
        ),
    ]
