# Generated by Django 2.1.7 on 2020-04-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aerodromes', '0003_auto_20200420_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codedocument', models.CharField(max_length=100, verbose_name='Référence document')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre document')),
                ('datedocument', models.DateField(verbose_name='Date de production du document ')),
                ('fichierdocument', models.FileField(default='fichierdefaut.pdf', upload_to='documents/%Y/%m/%d/', verbose_name='Document Inspection')),
                ('departementdocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerodromes.Departementac', verbose_name='Département  en charge')),
            ],
        ),
    ]
